- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    
- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes


