---
- name: Create Multipass VM 
  hosts: localhost
  vars_files:
    - vm-config.yaml
  tasks:
  - name: Create cloud-init file
    include_tasks: create-cloudinit.yaml

  - name: Create Multipass VM 
    include_tasks: create-or-update-multipass-vm.yaml
 